import type { Theme } from "../types/theme";

export const DEFAULT_THEME: Theme = {
  color_scheme: "custom",
  display_name: "自定义主题",
  back_color: "#242424",
  border_color: "#1f1f1f",
  text_color: "#f2f2f2",
  candidate_text_color: "#f2f2f2",
  candidate_back_color: "#00000000",
  candidate_shadow_color: "#00000000",
  hilited_candidate_text_color: "#111111",
  hilited_candidate_back_color: "#a78bfa",
  hilited_candidate_border_color: "#00000000",
  hilited_candidate_shadow_color: "#00000000",
  hilited_label_color: "#ffffff",
  hilited_comment_text_color: "#ffffff",
  hilited_mark_color: "#ff6b6b",
  label_color: "#bbbbbb",
  comment_text_color: "#888888",
  hilited_text_color: "#ffffff",
  hilited_back_color: "#4c1d95",
  hilited_shadow_color: "#00000000",
  shadow_color: "#00000033",
  nextpage_color: "#a0a0a0",
  prevpage_color: "#a0a0a0",
  font_face: "Inter, system-ui",
  label_font_face: "Inter, system-ui",
  comment_font_face: "Inter, system-ui",
  font_point: 16,
  label_font_point: 13,
  comment_font_point: 12,
  corner_radius: 12,
  border_width: 2,
  margin_x: 14,
  margin_y: 10,
  spacing: 12,
  candidate_spacing: 20,
  hilite_padding: 12,
  shadow_radius: 12,
  shadow_offset_x: 0,
  shadow_offset_y: 6,
  round_corner: 10,
  padding: 12
};
